### ISSUE TITLE
Cambiar Widget reproductor radio

### ISSUE THREAD

**Issue by valentinguillan** [indecisovampiro/indecisovampiro.com.ar#20]
Hola, tengo armado en un reproductor en figma. Hay chances de cambiar ese que hay en la pagina ? 

<img width="780" alt="Captura de Pantalla 2021-08-17 a la(s) 03 48 09" src="https://user-images.githubusercontent.com/49484934/129677198-a5e4896e-45db-4ca0-88b1-477b7fe25173.png">

**Comment by sobrinojulian** [comment]
Si lo cambio. Dale, mañana lo hago. no hace falta que me lo pases en figma.
Me voy a fijar si encuentro un widget ya armado que sea parecido, por lo menos para cambiarlo por algo rapido.
Despues lo hago a manopla asi queda igual al tuyo.

**Comment by sobrinojulian** [comment]
Si lo cambio. Dale, mañana lo hago. no hace falta que me lo pases en figma.
Me voy a fijar si encuentro un widget ya armado que sea parecido, por lo menos para cambiarlo por algo rapido.
Despues lo hago a manopla asi queda igual al tuyo.

**Comment by valentinguillan** [comment]
Ahí puse uno que arme en el figma, por si sirve. Después hay que ver el tema del link de transmisión de radio no ? mi idea es que en la parte de video se reproduzca alguna visual.  pero paralelo a la "señal" del streaming de la radio. No sé si se entiende jaja.

<img width="664" alt="Captura de Pantalla 2021-08-25 a la(s) 03 10 54" src="https://user-images.githubusercontent.com/49484934/130735937-0a7a8892-59c2-49fb-99aa-8e877ec0fd14.png">

**Comment by valentinguillan** [comment]
Dale tranqui :)

**Comment by sobrinojulian** [comment]
Usamos el iframe nuevo
