### ISSUE TITLE
/novedades

### ISSUE THREAD

**Issue by valentinguillan** [indecisovampiro/indecisovampiro.com.ar#27]
La seccion noticias que me mostraste está buena para usar. Pero se puede llamar "novedades" En lugar de noticias?

**Comment by sobrinojulian** [comment]
Mientras vayas subiendo cosas, vemos si hay algo raro. Faltan dos cosas que serian:
- poder ir al post en si (ejemplo el 1ro esta aca: https://indecisovampiro.com.ar/p/20210730024421/)
- Agregar un boton de siguiente pagina o que se vayan cargando mientras scrolleas ala instagram/ muro de facebook porque de momento cargan todos, y si hay 100 noticias va a cargar todo de una

**Comment by valentinguillan** [comment]
Hola. No puedo cargar Novedades nuevas.   No aparecen. 

En cms está solo esa que acabo de publicar. Pero en la web no se ve 
<img width="726" alt="Captura de Pantalla 2021-12-14 a la(s) 11 51 17" src="https://user-images.githubusercontent.com/49484934/146021484-a745a460-7df3-4517-9b04-fffe7fa4ccfb.png">

**Comment by sobrinojulian** [comment]
hoy a la anoche lo veo

**Comment by sobrinojulian** [comment]
@valentinguillan ahi creo que esta esto. lo demas lo voy a ir haciendo en la semana. lo que te iba a pedir es que cuando subas imagenes, de comprimirlas en una pagina como esta: https://tinypng.com/.

Eventualmente estaria bueno que se optimice solo, pero bueno mientras tanto hay que hacerlo manual. Ese flyer ultimo que subiste pesa 900kbs y es mucho. deberia pesar 50kbs ponele. Saludos
