### ISSUE TITLE
pasas el logo de editorial vampira en figma o svg/png por aca

### ISSUE THREAD

**Issue by sobrinojulian** [indecisovampiro/indecisovampiro.com.ar#36]
![Screenshot_2021-09-10_04-49-42](https://user-images.githubusercontent.com/34169391/132819683-0af0f0a6-886a-4cd0-b8c7-227629708122.png)
porfavor @valentinguillan

**Comment by valentinguillan** [comment]
Ya los puse en figma. En negro y en blanco

<img width="648" alt="Captura de Pantalla 2021-09-14 a la(s) 10 43 38" src="https://user-images.githubusercontent.com/49484934/133268816-7705322a-c71a-43a2-b20c-7fce9ce11030.png">
