### ISSUE TITLE
Netlify  cms no puedo publicar

### ISSUE THREAD

**Issue by valentinguillan** [indecisovampiro/indecisovampiro.com.ar#38]
Buenas, Quiero cambiar cosas dentro del cms y aparecen errores. a veces ni me deja entrar.
Y bueno, no puedo agregar ni modificar nada de la pagina :(

<img width="816" alt="Captura de Pantalla 2021-11-18 a la(s) 16 15 57" src="https://user-images.githubusercontent.com/49484934/142484111-c6d3ebd9-fc7c-49d8-a5b3-e0255a220a72.png">

<img width="398" alt="Captura de Pantalla 2021-11-18 a la(s) 11 46 43" src="https://user-images.githubusercontent.com/49484934/142484899-f0f9c90b-6972-4dd1-a7db-4c7c977e539c.png">

**Comment by sobrinojulian** [comment]
fijate ahora
