### ISSUE TITLE
Cambiar reproductor radio

### ISSUE THREAD

**Issue by valentinguillan** [indecisovampiro/indecisovampiro.com.ar#39]
Hola Juli, che cambiamos de host de radio vampira. Y este nos da un código con el reproductor y ya enlazado con la radio según tengo entendido. Ahí te muestro capturas y el codigo por si sirve de algo o no sé.

<img width="714" alt="Captura de Pantalla 2021-11-19 a la(s) 04 47 55" src="https://user-images.githubusercontent.com/49484934/142585237-0d618499-7363-412b-9726-8cbde48a0741.png">
<img width="696" alt="Captura de Pantalla 2021-11-19 a la(s) 04 48 01" src="https://user-images.githubusercontent.com/49484934/142585230-5e416323-c659-4328-bdd4-f6b204dddaad.png">

------------------

<style>
            .force-size-height,.force-size{
              min-height: initial !important;
              max-height: initial !important;
            }
            .force-size-width,.force-size{
              min-width: initial !important;
              max-width: initial !important;
            }
            </style><div style="transition-property:all;transition-duration:0.5s;width:540px;height:75px;max-width:1000px;max-height:200px;min-width:400px;min-height:70px" voxs="" voxs-ya="voxs-ya">
              <iframe id="ekng48825" style="width:100%;height:100%;border:0" src="https://streamingradioplayer.inovanex.com/s#/player-1#tema=5b9c07b2a2892d736b3871f9&amp;id=ekng48825&amp;c=915ea9be2ec0f2d05b64bb43e1bab1f9e2beb1919ee1a678a9270c09c495730a&amp;d=25a10fb2598a2ca6e8dc1de5b31304eaebced465a2eb1d5c28069b748b152c47d173687b241db7f1e1f07bcb83ea2e2e78dfde975dfd69369cf42718b226b06e0cfb267809a1eeb92f6a0bfc48f88d3c6a8170fc3de60c6fb7ff9094baba514850168de6615753165bbc646dd354beb78edd02bffc76ae539341c52daa9ec4967c132d2d5a49cf1bc057fe012d8ecdbaeeacf9a559b3a0cb4dc0b9e087aba653cddfb5a793b9e8bf0894f72e3a82b07ac277603302bd2acbe4e44ee7805cd6c26fd8d2d9e777ce0b3664a69ce42282f43a5e7c4949f5139e6ad79c40cad93756cb7e6dc26537ad3f965f8051626971955f3061b29374e0310129f091eb511755031cd745d0cf72a575a9f7fac05c0b627736fd480d3b6ee2e9c52ea24fe422b6387562203ce96374aa6a7c63acfe8b95bcaa0ef6498cb1e45ac10d1268fec8a5510f01f12415f2815b1d07e13a88a47d" voxs="" class="radio-player-frame" voxs-ya="voxs-ya">
              </iframe>
              <script src="https://streamingradioplayer.inovanex.com/site/inovanex-player/static/e/0/js/radio.client.js?d=454807" voxs="" type="text/javascript" voxs-ya="voxs-ya"></script>
            </div>

**Comment by sobrinojulian** [comment]
Perfecto wil hoy me hago un ratito y lo cambio

**Comment by sobrinojulian** [comment]
perdona la demora @valentinguillan . si esta bien cerra el issue. sino decime. abrazo

**Comment by valentinguillan** [comment]
Mirá algo así como tiene esta web sería.  https://www.groovefm.com.ar/  Deberíamos modificar un poco las distancias entre las cosas. no? porque queda muy vacío. Mucho espacio en negro

<img width="1416" alt="Captura de Pantalla 2021-11-25 a la(s) 01 42 01" src="https://user-images.githubusercontent.com/49484934/143380802-6a747e58-6ca0-4004-98d7-c87df64ceb48.png">


Vi que ese tiene de bueno que podes ir navegando por el sitio sin que se corte la transmisión. Eso se puede lograr?

**Comment by sobrinojulian** [comment]
Dalee wil buenisimo. creo dos issues al respecto y el en estos dias lo hago
