### ISSUE TITLE
Agregar app store

### ISSUE THREAD

**Issue by valentinguillan** [indecisovampiro/indecisovampiro.com.ar#42]
Hola, habría que agregar el botón de app store también. Y el link de descarga dentro de settings en el cms.

Algo así:
<img width="592" alt="Captura de Pantalla 2021-12-01 a la(s) 19 04 41" src="https://user-images.githubusercontent.com/49484934/144321519-06b59fd6-9f21-408d-ab8d-604e8488f3a0.png">

El link de app store es:

https://apps.apple.com/es/app/radio-vampira/id1597176179

Los botones los dejé en figma.

<img width="525" alt="Captura de Pantalla 2021-12-01 a la(s) 19 11 08" src="https://user-images.githubusercontent.com/49484934/144322346-fad19bfe-4c0e-4355-9ad4-69df2ca9e37e.png">

**Comment by sobrinojulian** [comment]
d1

**Comment by sobrinojulian** [comment]
cualquier cosa avisa y lo reabrimos

**Comment by valentinguillan** [comment]
Puede cambiar el texto? que diga :
"Y seguí escuchando Radio Vampira"
<img width="211" alt="Captura de Pantalla 2021-12-02 a la(s) 02 23 17" src="https://user-images.githubusercontent.com/49484934/144362698-277bdcff-818f-41de-9efb-394be57ca019.png">

Porque el que está dice "sin drama" al final y pinta sacar eso ya jaj

**Comment by sobrinojulian** [comment]
Es una imagen que esta [aca](https://github.com/indecisovampiro/indecisovampiro.com.ar/blob/main/static/images/bajate-la-app.svg). Podes hacerme otra igual? y la cambio. Eso lo habia hecho svg al final porque era mas facil que estar cambiando el font size.

**Comment by sobrinojulian** [comment]
> Puede cambiar el texto? que diga : "Y seguí escuchando Radio Vampira" <img alt="Captura de Pantalla 2021-12-02 a la(s) 02 23 17" width="211" src="https://user-images.githubusercontent.com/49484934/144362698-277bdcff-818f-41de-9efb-394be57ca019.png">
> 
> Porque el que está dice "sin drama" al final y pinta sacar eso ya jaj

listo.
