### ISSUE TITLE
Imagen Radio Inicio y banner bajate la app

### ISSUE THREAD

**Issue by valentinguillan** [indecisovampiro/indecisovampiro.com.ar#43]
_Hola Juli, se puede cambiar esas imágenes del inicio? Que el que dice "Radio Vampira" quede un rato y después se cambie a los otros logos? Pero que el de radio en vivo quede mas tiempo?

_Y cambiar el fondo de lo que dice "bajate la app"

Te dejo todo en figma. Avisame cualquier cosa.

<img width="569" alt="Captura de Pantalla 2021-12-06 a la(s) 20 08 03" src="https://user-images.githubusercontent.com/49484934/144937207-42dceb1b-5be8-4671-9dee-eb0427f92901.png">

<img width="650" alt="Captura de Pantalla 2021-12-06 a la(s) 20 08 43" src="https://user-images.githubusercontent.com/49484934/144937266-2aa58cd7-c4b4-4a8f-bfe1-e1d916b4b70f.png">

<img width="420" alt="Captura de Pantalla 2021-12-06 a la(s) 20 07 34" src="https://user-images.githubusercontent.com/49484934/144937161-5efdced8-7778-46b0-bd57-9260faf63b26.png">

**Comment by sobrinojulian** [comment]
dale, buenisimo. bancame al finde y lo hago. abrazo

**Comment by sobrinojulian** [comment]
hola @valentinguillan, estaria bueno si me agregas este (de la imagen) sin el fondo. sirve mejor para el responsive. hoy voy a tratar de hacer esto. saludos
![asd](https://user-images.githubusercontent.com/34169391/145723737-de511761-a037-4c47-a58a-29580ae6fc70.png)

**Comment by sobrinojulian** [comment]
Estan en bucle cada 8 segundos, y los margenes verticales funcionan medio raro depende el tamaño de la pantalla. pero zafa. cualquier cosa decime.
> Pero que el de radio en vivo quede mas tiempo?
Fui por la facil y es todo cada 8 seg. si queres que sea asi hacemos otro issue y despues lo veo

**Comment by valentinguillan** [comment]
Esta bastante bien. La imagen sin fondo está en Figma.

**Comment by sobrinojulian** [comment]
Me falto cambiarle el color a los fondos esos celestes. Despues lo agrego y hago lo de los links
