### ISSUE TITLE
Enlaces en carousel (los logos)

### ISSUE THREAD

**Issue by valentinguillan** [indecisovampiro/indecisovampiro.com.ar#45]
Se puede hacer que cada logo sea un enlace a otro lado?

<img width="279" alt="Captura de Pantalla 2021-12-13 a la(s) 12 57 41" src="https://user-images.githubusercontent.com/49484934/145845209-92db8212-09b6-45e1-a55d-d01b24cdc85f.png">

https://www.8astdf.com/banos-quimicos
<img width="190" alt="Captura de Pantalla 2021-12-13 a la(s) 12 58 00" src="https://user-images.githubusercontent.com/49484934/145845266-7eb049b2-89e9-47a9-bdf1-94c362c86ce2.png">

https://www.instagram.com/labo.mariee/

**Comment by sobrinojulian** [comment]
d1

**Comment by sobrinojulian** [comment]
Me falta que me pases este, en png/svg, sin el fondo. Ponelo en el figma plz. asi va a quedar mejor, 
@indecisovampiroweb me pones eso en el figma, pero sin el fondo, en png o svg plz.
![image](https://user-images.githubusercontent.com/34169391/161201034-3df4e551-da8a-4d3e-ab10-6ead07fdfd9e.png)

Cualquier cosa respecto al carousel dejo este abierto y comentame
@indecisovampiroweb

**Comment by indecisovampiroweb** [comment]
Ahí lo puse, estaba pero era blanco sobre fondo blanco.


Fijate que en los costados se ve así. Y si pueden ser mas chicos los logos

<img width="1106" alt="Captura de Pantalla 2022-04-01 a la(s) 18 48 41" src="https://user-images.githubusercontent.com/102713074/161345714-3f25af5d-b895-49cb-85e3-166f9457682d.png">

**Comment by sobrinojulian** [comment]
# Falta
- [ ] El fondito negro transparente entre el logo y el fondo
- [ ] Arreglar que mientras carga se ven los 3 slides
- [ ] CMS

Cualquier cosa que falte o se te ocurra decime. Para el carousel use [esta](https://flickity.metafizzy.co/options.html) libreria, fijate las opciones que tiene por si queres un dia cambiarle algo, es facil ya esta hecho por ese chabon.

Despues de esto me queda pendiente: arreglar el #49 reproductor que rompe la app, y las paginas que redirige #48.
Abrazo @indecisovampiroweb

**Comment by sobrinojulian** [comment]
ahi esta todo wil. cualquier error o cosita que veas pregunta, sino cerramos el issue. saludos

**Comment by indecisovampiroweb** [comment]
Hola, recien veo que el enlace a Skate shop te lleva a otra tienda que se llama 690 jaja
Este es el posta:

https://www.instagram.com/690skateshop/

**Comment by sobrinojulian** [comment]
Ahi ta, lo hice desde el CMS, hay una opcion nueva: "Carousel". Esta media fea y la tengo que arreglar, pero funciona. saludos
