### ISSUE TITLE
Si todos los programas estan invisibles esconder la <section>

### ISSUE THREAD

**Issue by sobrinojulian** [indecisovampiro/indecisovampiro.com.ar#46]
## Ahora:
![XXX](https://user-images.githubusercontent.com/34169391/145864120-eb9e995f-6c9f-41e8-9d54-b29ab3a2c9e9.png)

## Despues:
![XXX2](https://user-images.githubusercontent.com/34169391/145864141-090ec55b-18b5-4d95-b411-88ec836eb301.png)

**Comment by valentinguillan** [comment]
Buenisimo que lo viste. Te lo iba a decir pero no quería joder
