### ISSUE TITLE
Pedir la url del stream de la radio, para no usar el <iframe>

### ISSUE THREAD

**Issue by sobrinojulian** [indecisovampiro/indecisovampiro.com.ar#50]
> Estaria bueno si es posible y tenes contacto con los chabones de tener la url de la radio, como tenia el proveedor anterior, cosa de no tener que usar un iframe que son lentos y considerados una mala practica para algo tan central como el widget ese. En lo posible estaria bueno si lo puedo sacar. Si no se puede capaz lo puedo sacar inspeccionando el iframe, pero seria mas facil si me lo pasan.

**Comment by valentinguillan** [comment]
https://cdn.instream.audio/:9345/stream

**Comment by valentinguillan** [comment]
Era eso lo que necesitabas ?

**Comment by sobrinojulian** [comment]
si! gracias
