### ISSUE TITLE
Modificar Banner de titulo

### ISSUE THREAD

**Issue by indecisovampiroweb** [indecisovampiro/indecisovampiro.com.ar#57]
Hola juli, tenemos un nuevo logo en indeciso vampiro. Para modificar el banner del titulo.
Ahi te muestro unas capturas. Las imagenes las dejé en Figma

<img width="1434" alt="Captura de Pantalla 2022-07-04 a la(s) 18 01 30" src="https://user-images.githubusercontent.com/102713074/177216157-5d06afdb-b902-48ee-b27d-ef60e3727ce9.png">

<img width="731" alt="Captura de Pantalla 2022-07-04 a la(s) 18 17 15" src="https://user-images.githubusercontent.com/102713074/177217262-a06130d8-ba12-4a3e-8551-3aaaf49374d8.png">

<img width="728" alt="Captura de Pantalla 2022-07-04 a la(s) 18 16 59" src="https://user-images.githubusercontent.com/102713074/177217236-4301a9b9-85cc-41a7-9ae2-f01f086109c2.png">

**Comment by sobrinojulian** [comment]
ahi esta wil. cualquier cosa, avisame y lo arreglo, sino cerra el issue. y la segunda quincena de julio voy a estar al pedo asique cualquier cosa que se te ocurra anda creando issues asi y las voy arreglando. hay un par de issues pendientes y cosas que todavia me falta.
abrazo!

**Comment by indecisovampiroweb** [comment]
Buenisimo, quedó genial. Cualquier cosa te voy escribiendo por acá ;)
